<a href="https://colab.research.google.com/github/BLayus/Data_Folia/blob/main/Data_Folia_Concentra_mas_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Concentra mas Numpy

Exercícios Data Folia Utilizando Numpy

In [ ]:
import numpy as np

In [ ]:
# Criando um vetor com os seguintes valores [1,2,3,4,5], chame-o de vetA

vetA = np.array([1, 2, 3, 4, 5])
vetA

array([1, 2, 3, 4, 5])

In [ ]:
# Exiba os 3 primeiros elementos

print(vetA[:3])

[1 2 3]


In [ ]:
# Exiba todos os valores após o quinto elemento

print(vetA[5:])

[]


In [ ]:
# Exiba os 3 últimos elementos

print(vetA[-3:])



[3 4 5]


In [ ]:
# Exiba os valores de vetA entre o 5 elemento até o penúltimo elemento

vetA[-3:5]

array([3, 4, 5])

In [ ]:
# Crie uma matriz 5x5

m5 = np.arange(25).reshape(5,5)
m5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Exiba a matriz inteira

m5.shape

(5, 5)

In [ ]:
# Exiba todos os elementos da coluna 3

m5[0:5,2]

array([ 2,  7, 12, 17, 22])

In [ ]:
# Exiba todos os elementos da linha 2

m5[1,0:5]

array([5, 6, 7, 8, 9])

In [ ]:
# Exiba todos os elementos das 2 primeiras colunas

m5[:, :2]

array([[ 0,  1],
       [ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])

In [ ]:
# Exiba todos os elementos das 2 primeiras linhas

m5[:2, :]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
# Exiba apenas os elementos das 2 últimas linhas e das 4 últimas colunas

m5[-2: ,-4:]

array([[16, 17, 18, 19],
       [21, 22, 23, 24]])

In [ ]:
# Crie uma função que receba dois vetores e realize a soma de seus valores

vet1 = np.array([2, 4, 6, 8])
vet2 = np.array([1, 3, 5, 7])
vet1 + vet2

array([ 3,  7, 11, 15])

In [ ]:
def somavetores(vetX, vetY):
  for i in vetX:
    return vetX + vetY

In [ ]:
somavetores(vet1,vet2)


array([ 3,  7, 11, 15])

In [ ]:
# Generalize a função acima para que ela receba uma string representando a operação a ser executada: '+' ou '-'

input = input('+ -')

def somavetores(vetX, vetY):
  for i in vetX:
    if input == '+':
     return vetX + vetY
    else:
     return vetX - vetY

TypeError: ignored

In [ ]:
somavetores(vet1, vet2)

UnboundLocalError: ignored

In [ ]:
# Como calcular a média dos valores de uma matriz

m5.mean()

12.0

In [ ]:
# Calcule apenas a média das linhas

m5.mean(axis=1)

array([ 2.,  7., 12., 17., 22.])

In [ ]:
# Calcule apenas a média das colunas

m5.mean(axis=0)

array([10., 11., 12., 13., 14.])